datasource.url=${DATASOURCE_URL}
datasource.username=${DATASOURCE_USERNAME}
datasource.password=${DATASOURCE_PASSWORD}
datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}
anthropic.api.key=${ANTHROPIC_API_KEY}
jwt.secret=${JWT_SECRET}
jwt.token-timeout-seconds=108000
spring.devtools.livereload.enabled=false

