
datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.profiles.active=${SPRING_PROFILE:local}
server.port=${PORT:8080}
spring.devtools.livereload.enabled=false
anthropic.api.key=${anthropic.api.key}
jwt.secret=${jwt.secret}
jwt.token-timeout-seconds=108000